// Copyright 2026 Atakku <https://atakku.dev>
//
// This project is dual licensed under MIT and Apache.

apply from: 'https://raw.githubusercontent.com/Atakku/gradle/v51/neoforge_build.gradle'

project(':common').repositories {
  maven {
    url "https://maven.squiddev.cc"
    content {
        includeGroup("cc.tweaked")
    }
  }
}

project(':common').dependencies {
  compileOnly("cc.tweaked:cc-tweaked-$minecraft_version-common-api:$cct_version")
  implementation("cc.tweaked:cc-tweaked-$minecraft_version-common:$cct_version")
  jarJar(implementation("io.github.jaredmdobson:concentus:1.0.2"))
  additionalRuntimeClasspath("io.github.jaredmdobson:concentus:1.0.2")
}
